In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model as lr
import numpy as np

In [2]:
data=pd.read_csv("sleep.csv",sep=',')
data

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,None
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,None
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [3]:
#pretraitement des donnÃ©es
data = data.drop('Person ID',axis=1)

In [4]:
#modification des donnÃ©es de la colonne Sleep Disorder
for i in range(374):
    if data['Sleep Disorder'].iloc[i] == 'None':
        data['Sleep Disorder'].iloc[i] = 0.001
    elif data['Sleep Disorder'].iloc[i] == 'Sleep Apnea':
        data['Sleep Disorder'].iloc[i] = 0.599;
    elif data['Sleep Disorder'].iloc[i] == 'Insomnia':
        data['Sleep Disorder'].iloc[i] = 0.999

C:\Users\HPPAVI~1\AppData\Local\Temp/ipykernel_4756/1573731228.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Sleep Disorder'].iloc[i] = 0.001
C:\Users\HPPAVI~1\AppData\Local\Temp/ipykernel_4756/1573731228.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Sleep Disorder'].iloc[i] = 0.599;
C:\Users\HPPAVI~1\AppData\Local\Temp/ipykernel_4756/1573731228.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Sleep Disorder'].iloc[i] = 0.999

In [13]:
#modification des donnÃ©es de la colonne Gender
for i in range(374):
    if data['Gender'].iloc[i] == 'Female':
        data['Gender'].iloc[i] = 0.999
   # else :
    #      data['Gender'].iloc[i] == 0.999

C:\Users\HPPAVI~1\AppData\Local\Temp/ipykernel_4756/740792095.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Gender'].iloc[i] = 0.999

In [14]:
data

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder
0,0.001,27,6.1,6,42,6,77,4200,0.001
1,0.001,28,6.2,6,60,8,75,10000,0.001
2,0.001,28,6.2,6,60,8,75,10000,0.001
3,0.001,28,5.9,4,30,8,85,3000,0.599
4,0.001,28,5.9,4,30,8,85,3000,0.599
...,...,...,...,...,...,...,...,...,...
369,0.999,59,8.1,9,75,3,68,7000,0.599
370,0.999,59,8.0,9,75,3,68,7000,0.599
371,0.999,59,8.1,9,75,3,68,7000,0.599
372,0.999,59,8.1,9,75,3,68,7000,0.599
373,0.999,59,8.1,9,75,3,68,7000,0.599

In [17]:
#suppression des autres colonnes inutiles
data

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder
0,0.001,27,6.1,6,42,6,77,4200,0.001
1,0.001,28,6.2,6,60,8,75,10000,0.001
2,0.001,28,6.2,6,60,8,75,10000,0.001
3,0.001,28,5.9,4,30,8,85,3000,0.599
4,0.001,28,5.9,4,30,8,85,3000,0.599
...,...,...,...,...,...,...,...,...,...
369,0.999,59,8.1,9,75,3,68,7000,0.599
370,0.999,59,8.0,9,75,3,68,7000,0.599
371,0.999,59,8.1,9,75,3,68,7000,0.599
372,0.999,59,8.1,9,75,3,68,7000,0.599
373,0.999,59,8.1,9,75,3,68,7000,0.599

In [19]:
#suppression des autres colonnes inutiles
data

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder
0,0.001,27,6.1,6,42,6,77,4200,0.001
1,0.001,28,6.2,6,60,8,75,10000,0.001
2,0.001,28,6.2,6,60,8,75,10000,0.001
3,0.001,28,5.9,4,30,8,85,3000,0.599
4,0.001,28,5.9,4,30,8,85,3000,0.599
...,...,...,...,...,...,...,...,...,...
369,0.999,59,8.1,9,75,3,68,7000,0.599
370,0.999,59,8.0,9,75,3,68,7000,0.599
371,0.999,59,8.1,9,75,3,68,7000,0.599
372,0.999,59,8.1,9,75,3,68,7000,0.599
373,0.999,59,8.1,9,75,3,68,7000,0.599

In [20]:
data.iloc[250]

Gender                     0.999
Age                           45
Sleep Duration               6.8
Quality of Sleep               7
Physical Activity Level       30
Stress Level                   6
Heart Rate                    65
Daily Steps                 6000
Sleep Disorder             0.999
Name: 250, dtype: object

In [21]:
#preparation des donnÃ©es 
X_train = data.iloc[:,:8]
Y_train = data.iloc[:,8:9]
Y_train

    Sleep Disorder
0            0.001
1            0.001
2            0.001
3            0.599
4            0.599
..             ...
369          0.599
370          0.599
371          0.599
372          0.599
373          0.599

[374 rows x 1 columns]

In [22]:
#entrainement du modÃ¨le 
model = lr.LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [23]:
coef = model.coef_
init = model.intercept_

In [24]:
coef

array([[-1.66601375e-01,  3.51883059e-02, -1.60554083e-01,
        -4.04169960e-01,  3.69681057e-03, -1.92858728e-01,
        -3.42283624e-03, -3.95407597e-05]])

In [25]:
init

array([4.35942545])

In [35]:
#donnÃ©es test
x = np.ones(8)

for i in range(8):
    x[i] = X_train.iloc[0,i]
x.reshape(8,1)

array([[1.0e-03],
       [2.7e+01],
       [6.1e+00],
       [6.0e+00],
       [4.2e+01],
       [6.0e+00],
       [7.7e+01],
       [4.2e+03]])

In [36]:
y = init + coef.dot(x)
y

array([0.47342753])

In [32]:
data

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder
0,0.001,27,6.1,6,42,6,77,4200,0.001
1,0.001,28,6.2,6,60,8,75,10000,0.001
2,0.001,28,6.2,6,60,8,75,10000,0.001
3,0.001,28,5.9,4,30,8,85,3000,0.599
4,0.001,28,5.9,4,30,8,85,3000,0.599
...,...,...,...,...,...,...,...,...,...
369,0.999,59,8.1,9,75,3,68,7000,0.599
370,0.999,59,8.0,9,75,3,68,7000,0.599
371,0.999,59,8.1,9,75,3,68,7000,0.599
372,0.999,59,8.1,9,75,3,68,7000,0.599
373,0.999,59,8.1,9,75,3,68,7000,0.599